import { jsPDF } from "jspdf";

type Recommendation = { title: string; action: string };

export interface ReportApplication {
  id: string;
  full_name: string;
  status: string;
  created_at: string;
  reviewed_at?: string | null;
  arthsetu_score?: number | string | null;
  score_band?: string | null;
  default_probability?: number | string | null;
  recommended_credit_limit?: number | string | null;
  recommended_interest_rate?: number | string | null;
  annual_income?: number | string | null;
  monthly_net_income?: number | string | null;
  net_worth?: number | string | null;
  cibil_score?: number | string | null;
  loan_amount_requested?: number | string | null;
  purpose_of_credit?: string | null;
  recommendations?: unknown;
}

const inr = (v: number) =>
  new Intl.NumberFormat("en-IN", { maximumFractionDigits: 0 }).format(v);

const statusLabel: Record<string, string> = {
  approved: "Approved",
  override_approved: "Approved (officer reviewed)",
  rejected: "Not approved",
  override_rejected: "Not approved (officer reviewed)",
  pending: "Pending review",
};

export function downloadApplicationReport(app: ReportApplication) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  const line = (gap = 18) => {
    y += gap;
  };

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageW, 96, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("ArthSetu", margin, 52);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Credit Assessment Report", margin, 72);
  doc.setFontSize(9);
  doc.text(
    `Generated ${new Date().toLocaleDateString("en-IN")}`,
    pageW - margin,
    72,
    { align: "right" },
  );

  y = 132;
  doc.setTextColor(15, 23, 42);

  const heading = (text: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(text, margin, y);
    line(8);
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, y, pageW - margin, y);
    line(20);
  };

  const row = (label: string, value: string) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(110, 110, 110);
    doc.text(label, margin, y);
    doc.setTextColor(20, 20, 20);
    doc.setFont("helvetica", "bold");
    doc.text(value, pageW - margin, y, { align: "right" });
    line(22);
  };

  // Applicant
  heading("Applicant");
  row("Name", app.full_name || "—");
  row("Application ID", app.id);
  row("Submitted", new Date(app.created_at).toLocaleDateString("en-IN"));
  row(
    "Reviewed",
    app.reviewed_at ? new Date(app.reviewed_at).toLocaleDateString("en-IN") : "—",
  );
  row("Decision", statusLabel[app.status] ?? app.status);
  line(10);

  // Score
  heading("ArthSetu score");
  row("Score", String(Math.round(Number(app.arthsetu_score ?? 0))));
  row("Band", (app.score_band ?? "—").replace(/_/g, " "));
  row(
    "Probability of default",
    `${(Number(app.default_probability ?? 0) * 100).toFixed(1)}%`,
  );
  line(10);

  // Recommendation
  heading("Credit recommendation");
  row("Recommended credit limit", `₹${inr(Number(app.recommended_credit_limit ?? 0))}`);
  row("Indicative interest rate", `${app.recommended_interest_rate ?? "—"}% p.a.`);
  row("Loan requested", `₹${inr(Number(app.loan_amount_requested ?? 0))}`);
  row("Purpose", app.purpose_of_credit ?? "—");
  line(10);

  // Financial snapshot
  heading("Financial snapshot");
  row("Annual income", `₹${inr(Number(app.annual_income ?? 0))}`);
  row("Monthly net income", `₹${inr(Number(app.monthly_net_income ?? 0))}`);
  row("Net worth", `₹${inr(Number(app.net_worth ?? 0))}`);
  row("CIBIL score", String(app.cibil_score ?? "—"));
  line(10);

  // Recommendations
  const recs = Array.isArray(app.recommendations)
    ? (app.recommendations as Recommendation[])
    : [];
  if (recs.length > 0) {
    if (y > 680) {
      doc.addPage();
      y = margin;
    }
    heading("How to improve");
    recs.forEach((r) => {
      if (y > 760) {
        doc.addPage();
        y = margin;
      }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(20, 20, 20);
      doc.text(`• ${r.title}`, margin, y);
      line(15);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(90, 90, 90);
      const wrapped = doc.splitTextToSize(r.action, pageW - margin * 2 - 12);
      doc.text(wrapped, margin + 12, y);
      line(15 * wrapped.length + 8);
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "This report is generated by ArthSetu for informational purposes.",
    margin,
    doc.internal.pageSize.getHeight() - 30,
  );

  doc.save(`ArthSetu-report-${app.id.slice(0, 8)}.pdf`);
}
